### ISSUE TITLE
gpt야 여행블로그 프로젝트 이름 지어줘!

### ISSUE THREAD

**Issue by raheego** [raheego/nomardLog#4]
1. **여행일기장** (TravelDiary)
2. **방랑이야기** (WanderingStories)
3. **여행노트룸** (TravelNoteRoom)
4. **로밍플로우** (RoamingFlow)
5. **방황블로터** (WanderBlotter)
6. **지구둘러보기** (AroundTheGlobe)
7. **모험수첩** (AdventureChronicle)
8. **탐험하우스** (ExplorationHouse)
9. **노마드포스트** (NomadPost)
10. **여정서랍** (JourneyDrawer)
11. **탐험일기꾼** (ExplorerDiarist)
12. **방랑사설** (WanderingAnecdotes)
13. **일정마당** (ItinerarySquare)
14. **운명그림** (DestinySketch)
15. **모험극장** (AdventureTheater)

한국어로 표현된 이 이름들은 블로그와 여행을 결합하여 특별한 느낌을 주도록 노력했습니다. 여기서 선택하실 수 있는 이름 중에서 프로젝트의 콘셉트와 분위기에 맞는 것을 골라보세요!

**Comment by ldh0308** [comment]
9번 노마드포스트 좋아용

**Comment by parc02** [comment]
저도 노마드포스트!

**Comment by Jaelinny** [comment]
저는 1번이요!
